name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # This allows you to trigger the build manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: irrigation-app
          path: ${{ steps.buildozer.outputs.filename }}
